import java.io.File
import java.nio.file.Files
import org.checkerframework.plugin.gradle.CheckerFrameworkExtension

plugins {
    id("org.springframework.boot") version "3.5.16" apply false
    id("io.spring.dependency-management") version "1.1.6" apply false
    id("org.checkerframework") version "1.0.2" apply false
}

group = "top.focess"
version = "1.0.100"

// Centralized dependency versions shared across all subprojects
extra["jacksonVersion"] = "2.18.8"
extra["jeromqVersion"] = "0.6.0"
extra["slf4jVersion"] = "2.0.13"
extra["logbackVersion"] = "1.5.34"
extra["jlineVersion"] = "3.26.1"

// Null safety is a repository-wide compile contract. Unannotated references are nullable;
// JSpecify @NonNull opts individual contracts into non-nullness.
subprojects {
    pluginManager.withPlugin("java") {
        if (project.name == "veto-nullness-checker") return@withPlugin
        apply(plugin = "org.checkerframework")

        configure<CheckerFrameworkExtension> {
            version = "4.1.0"
            checkers = listOf("top.focess.veto.checker.VetoNullnessChecker")
        }

        dependencies {
            add("checkerFramework", "org.checkerframework:checker:4.1.0")
            add("checkerFramework", project(":veto-nullness-checker"))
        }

        tasks.withType<JavaCompile>().configureEach {
            // Checker analysis of the full source/test tree exceeds the default worker heap.
            options.forkOptions.memoryMaximumSize = "2g"
            // Compiler warnings are defects: keep the same zero-warning contract in every module
            // and for both production and test sources.
            options.compilerArgs.addAll(
                listOf(
                    // Veto never persists or exchanges Java-serialized objects. Throwable and
                    // Jackson base classes inherit Serializable, but their computed serial UID is
                    // not an application compatibility contract.
                    "-Xlint:all,-processing,-serial",
                    "-Werror",
                    // Checker Framework 4.1 reports JSpecify TYPE_USE annotations on nested
                    // record components as invalid when it reads javac's generated bytecode.
                    // This is an annotation-location interoperability false positive; it does
                    // not disable any nullness rule or diagnostic.
                    "-AignoreInvalidAnnotationLocations",
                ),
            )
            val checkerStubs = project.layout.projectDirectory.dir("config/checker").asFile
            val testStubs = rootProject.file("config/checker-test")
            val stubs = buildList {
                if (checkerStubs.isDirectory && checkerStubs.listFiles()?.isNotEmpty() == true)
                    add(checkerStubs.absolutePath)
                if (name == "compileTestJava" && project.name != "veto-terminal" && testStubs.isDirectory)
                    add(testStubs.absolutePath)
            }
            if (stubs.isNotEmpty()) {
                options.compilerArgs.add("-Astubs=${stubs.joinToString(File.pathSeparator)}")
            }
        }

        // Every published JVM artifact must carry the same license as the source repository.
        tasks.withType<Jar>().configureEach {
            from(rootProject.file("LICENSE")) {
                into("META-INF")
            }
        }
    }
}

// ── Local release packaging ──────────────────────────────────────────────────
// Assembles ONE versioned, self-contained bundle under release/veto-<version>/
// from the three modules: the executable Spring Boot core jar, the terminal
// distribution zip (application-plugin dist with bin/ launchers), launcher
// scripts for the core jar, and VERSION/README. Idempotent: wipes and
// rebuilds its own version directory, never touches other versions. release/
// is a local artifact (gitignored).
val releaseReadme = layout.buildDirectory.file("release-docs/README.md")
val generateReleaseReadme by tasks.registering {
    group = "release"
    description = "Renders the user-facing release README without building binaries."
    val template = layout.projectDirectory.file("RELEASE.md")
    val releaseVersion = project.version.toString()
    inputs.file(template)
    inputs.property("releaseVersion", releaseVersion)
    outputs.file(releaseReadme)
    doLast {
        val output = releaseReadme.get().asFile
        output.parentFile.mkdirs()
        output.writeText(template.asFile.readText().replace("@VETO_VERSION@", releaseVersion))
    }
}

val localRelease by tasks.registering {
    group = "release"
    description = "Assembles the versioned local release bundle under release/."
    dependsOn(":veto-core:bootJar", ":veto-terminal:distZip", ":veto-protocol:jar")
    dependsOn(generateReleaseReadme)
    val versionStr = project.version.toString()
    val outDir = layout.projectDirectory.dir("release/veto-$versionStr")
    val workspace = rootProject.projectDir.canonicalFile
    val releaseRoot = layout.projectDirectory.dir("release").asFile.canonicalFile
    val bootJar =
            project(":veto-core")
                    .layout
                    .buildDirectory
                    .file("libs/veto-core-$versionStr.jar")
    val distZip =
            project(":veto-terminal")
                    .layout
                    .buildDirectory
                    .file("distributions/veto-terminal-$versionStr.zip")
    val license = layout.projectDirectory.file("LICENSE")
    doLast {
        val out = outDir.asFile.canonicalFile
        require(releaseRoot.path.startsWith(workspace.path + File.separator))
        require(out.parentFile == releaseRoot)
        require(!Files.isSymbolicLink(outDir.asFile.toPath()))
        out.deleteRecursively()
        val coreDir = File(out, "core").apply { mkdirs() }
        val terminalDir = File(out, "terminal").apply { mkdirs() }
        bootJar.get().asFile.copyTo(File(coreDir, "veto-core.jar"))
        val terminalZip = distZip.get().asFile
        terminalZip.copyTo(File(terminalDir, terminalZip.name))
        license.asFile.copyTo(File(out, "LICENSE"))
        val dollar = "$"
        File(out, "start-core.bat")
                .writeText(
                        "@echo off\r\n" +
                                "rem Starts the veto-core server (visible console).\r\n" +
                                "java --enable-native-access=ALL-UNNAMED -jar \"%~dp0core\\veto-core.jar\" %*\r\n")
        File(out, "start-core.sh")
                .writeText(
                        "#!/bin/sh\n" +
                                "# Starts the veto-core server.\n" +
                                "exec java --enable-native-access=ALL-UNNAMED -jar \"" +
                                dollar +
                                "(dirname \"" +
                                dollar +
                                "0\")/core/veto-core.jar\" \"" +
                                dollar +
                                "@\"\n")
        File(out, "VERSION").writeText("component=veto\nversion=$versionStr\n")
        releaseReadme.get().asFile.copyTo(File(out, "README.md"))
        println("Local release assembled: ${out.absolutePath}")
    }
}

// Optional plugin artifacts are built separately from the core release. Operators install only
// the packages they choose under the backend's plugins/ directory.
val localPluginPackages by tasks.registering {
    group = "release"
    description = "Builds optional installable plugin directories under release/plugin-packages/."
    dependsOn(":veto-builtin:jar", ":veto-llm-providers:jar", ":veto-secret-protection:jar")
    val packages =
            listOf(
                    Triple("veto-builtin", "top.focess.builtin", "top.focess.veto.builtin.BuiltinPlugin"),
                    Triple(
                            "veto-llm-providers",
                            "top.focess.llm-providers",
                            "top.focess.veto.providers.LlmProvidersPlugin"),
                    Triple(
                            "veto-secret-protection",
                            "top.focess.secret-protection",
                            "top.focess.veto.secret.SecretProtectionPlugin"),
            )
    val versionStr = project.version.toString()
    val workspace = rootProject.projectDir.canonicalFile
    val root = layout.projectDirectory.dir("release/plugin-packages/$versionStr").asFile.canonicalFile
    val packageInputs =
            packages.associate { (module, _, _) ->
                val pluginProject = project(":$module")
                module to
                        Pair(
                                pluginProject.layout.buildDirectory.file("libs/$module-$versionStr.jar"),
                                pluginProject.configurations.getByName("runtimeClasspath"),
                        )
            }
    doLast {
        require(root.path.startsWith(workspace.path + File.separator))
        root.mkdirs()
        for ((module, id, entryPoint) in packages) {
            val folder = File(root, id).canonicalFile
            require(folder.parentFile == root)
            folder.mkdirs()
            val (artifact, runtimeClasspath) = packageInputs.getValue(module)
            val sourceJar = artifact.get().asFile
            val packageJar = File(folder, "plugin.jar")
            if (!packageJar.isFile || Files.mismatch(sourceJar.toPath(), packageJar.toPath()) != -1L)
                sourceJar.copyTo(packageJar, overwrite = true)
            val libraries = File(folder, "lib").apply { mkdirs() }
            val dependencies = runtimeClasspath.files
            for (dependency in dependencies) {
                if (!dependency.isFile || !dependency.name.endsWith(".jar")) continue
                if (dependency.name.startsWith("veto-api-")) continue
                if (dependency.name.startsWith("$module-")) continue
                val packagedLibrary = File(libraries, dependency.name)
                if (!packagedLibrary.isFile ||
                    Files.mismatch(dependency.toPath(), packagedLibrary.toPath()) != -1L
                ) dependency.copyTo(packagedLibrary, overwrite = true)
            }
            val displayName =
                    when (module) {
                        "veto-builtin" -> "Builtin Tools"
                        "veto-llm-providers" -> "LLM Providers"
                        else -> "Secret Protection"
                    }
            File(folder, "plugin.json")
                    .writeText(
                            """{"schemaVersion":1,"id":"$id","name":"$displayName","version":"$versionStr","type":"java","entryPoint":"$entryPoint","artifact":"plugin.jar"}
""")
        }
        println("Optional plugin packages assembled: ${root.absolutePath}")
    }
}
